<Resource>
    Label:
        size_hint_x:.1
    BoxLayout:
        Label:
            text: root.primary
        Label:
            text: root.trinomial
        Button:
            text: str(root.rc)
            on_release: root.callmenu(1)
        Button:
            text: str(root.dc)
            on_release: root.callmenu(2)
        Button:
            text: str(root.gc)
            on_release: root.callmenu(3)
    Label:
        size_hint_x:.1
